import _ from "lodash";
export default {
	// backbone
	bind: _.bind,
	clone: _.clone,
	create: _.create,
	defaults: _.defaults,
	defer: _.defer,
	each: _.each,
	escape: _.escape,
	extend: _.extend,
	has: _.has,
	isArray: _.isArray,
	isEmpty: _.isEmpty,
	isEqual: _.isEqual,
	isFunction: _.isFunction,
	isObject: _.isObject,
	isRegExp: _.isRegExp,
	isString: _.isString,
	iteratee: _.iteratee,
	keys: _.keys,
	map: _.map,
	matches: _.matches,
	once: _.once,
	pick: _.pick,
	result: _.result,
	some: _.some,
	uniqueId: _.uniqueId,

	// backbone collection/model methods
	// chain: _.chain,
	// countBy: _.countBy,
	// difference: _.difference,
	// drop: _.drop,
	// every: _.every,
	// filter: _.filter,
	// find: _.find,
	// findIndex: _.findIndex,
	// findLastIndex: _.findLastIndex,
	// first: _.first,
	// forEach: _.forEach,
	// groupBy: _.groupBy,
	// head: _.head,
	// includes: _.includes,
	indexOf: _.indexOf,
	// initial: _.initial,
	// invert: _.invert,
	// invoke: _.invoke,
	// last: _.last,
	// lastIndexOf: _.lastIndexOf,
	// max: _.max,
	// min: _.min,
	// omit: _.omit,
	// partition: _.partition,
	// reduce: _.reduce,
	// reduceRight: _.reduceRight,
	// reject: _.reject,
	// rest: _.rest,
	// sample: _.sample,
	// shuffle: _.shuffle,
	// size: _.size,
	// sortBy: _.sortBy,
	// tail: _.tail,
	// take: _.take,
	// toArray: _.toArray,
	// without: _.without,

	// backbone-react-component
	partial: _.partial,
	values: _.values,
};